### ISSUE TITLE
Sensor Error

### ISSUE THREAD

**Issue by guybrush06** [rchrch/homebridge-mhacwifi1-lan#9]
Seeing the below error in Homebridge

Unhandled sensor item { uid: 6, value: 10, status: 0 }

My device model is below if that helps any

FJ-AC-WIFI-1B

**Comment by rchrch** [comment]
I don't think that particular model works with my plugin.  It's designed for the MH-AC-WIFI-1 control module which goes into the Mitsubishi Heavy aircon.  I assume (given the name) you have a Fujitsu split system.  Not sure I can help as I only have the Mitsubishi units in my house.  Sorry... :)

**Comment by guybrush06** [comment]
Yeah its Fujistu... it does work really well.. just logs that error constantly. No big deal I guess

**Comment by rchrch** [comment]
I think the underlying hardware/firmware is made by Intesis so that doesn't surprise me.  I can look into adding an option to suppress the error message when it gets an unknown type.  Not sure how you're running homebridge, but if you want to prevent the message from happening in your version you can simply remove this line of code from the plugin source on your copy:

https://github.com/rchrch/homebridge-mhacwifi1-lan/blob/915904940634dd2f88bd4aade83fe9ca427dad06/src/accessories/device.ts#L294

You should be able to find it in a directory like node_modules/homebridge-mhacwifi1-lan/accessories/device.ts in your setup.  Just restart the plugin (or homebridge) to pick up the change.  I don't have a lot of time to dedicate to this project right now to add a specific config option so this might be your best option.

**Comment by guybrush06** [comment]
I managed to find another plugin for the Fujistu so you can close this one off.
Thanks for replying
